apiVersion: v1
kind: service
metaData: 
 name: backend

spec:
  type: ClusterIp
  ports:
  - port: 80 // the port where service is exposed 
    targetPort: 80 // port where the backend expose 
  selector:
   app: myapp
   type: back-end

  ##the service is accessbile by other pod (frontend for exemlpe) byhisIp and his port .
## and theis service wil communicate with backend ports 


  ##kubectl create service -f service-defintion.yml 
  ##kubectl get sv