apiVersion: v1
kind: service
metaData: 
 name: my-app-service

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePot: 30004
  selector:
   app: myapp


  ##kubectl create service -f service-defintion.yml 
  ##kubectl get sv