appVersion: apps/v1
kind: Deployment
metadata: 
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replication: 1
  selector:
    matchLabels:
      name: voting-app-pod
  template:
    metadata: 
    name: voting-app-pod
    labels:
      name: voting-app-pod
      app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
          -containerPort: 80
  
